#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# setup_simulation_local.sh
# Creates the LocalStack SQS queue + DynamoDB metrics table used by the local
# simulation pipeline (start_simulation -> f1-consumer -> metrics-exporter).
#
# Run from project/ after LocalStack is healthy (make start / make all).
# Writes project/.local/simulation.env for docker-compose (f1-consumer).
# ---------------------------------------------------------------------------
set -euo pipefail

ENDPOINT="http://localhost:4566"
REGION="us-east-1"
ACCOUNT="000000000000"
QUEUE_NAME="racetrack-local-simulation-events"
TABLE_NAME="racetrack-local-simulation-metrics"
ENV_DIR=".local"
ENV_FILE="${ENV_DIR}/simulation.env"

awslocal() {
  aws --endpoint-url="$ENDPOINT" --region="$REGION" "$@"
}

mkdir -p "$ENV_DIR"

echo "Waiting for LocalStack (dynamodb + sqs)..."
until curl -sf "$ENDPOINT/_localstack/health" \
  | python3 -c "import sys,json; s=json.load(sys.stdin).get('services',{}); exit(0 if s.get('dynamodb') in ('running','available') and s.get('sqs') in ('running','available') else 1)" \
  2>/dev/null; do
  printf "."
  sleep 2
done
echo " ready."

echo "Creating SQS queue ${QUEUE_NAME}..."
awslocal sqs create-queue --queue-name "$QUEUE_NAME" >/dev/null 2>&1 || true
QUEUE_URL=$(awslocal sqs get-queue-url --queue-name "$QUEUE_NAME" --query QueueUrl --output text)
echo "  Queue URL: ${QUEUE_URL}"

echo "Creating DynamoDB table ${TABLE_NAME}..."
if ! awslocal dynamodb describe-table --table-name "$TABLE_NAME" >/dev/null 2>&1; then
  awslocal dynamodb create-table \
    --table-name "$TABLE_NAME" \
    --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
    --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
    --billing-mode PAY_PER_REQUEST >/dev/null
  awslocal dynamodb wait table-exists --table-name "$TABLE_NAME"
fi
awslocal dynamodb update-time-to-live \
  --table-name "$TABLE_NAME" \
  --time-to-live-specification "Enabled=true,AttributeName=ttl" >/dev/null 2>&1 || true
echo "  Table ready."

# docker-compose (f1-consumer on racetrack network) uses localstack hostname.
DOCKER_QUEUE_URL="${QUEUE_URL//localhost:4566/localstack:4566}"
DOCKER_QUEUE_URL="${DOCKER_QUEUE_URL//localhost.localstack.cloud/localstack}"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup_simulation_local.sh — do not commit.
SQS_QUEUE_URL=${DOCKER_QUEUE_URL}
SQS_ENDPOINT=http://localstack:4566
DYNAMODB_TABLE=${TABLE_NAME}
DYNAMODB_ENDPOINT=http://localstack:4566
AWS_DEFAULT_REGION=${REGION}
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test
TTL_DAYS=7
EOF

# Host-facing URL for SAM local / curl (Lambda containers use host.docker.internal).
HOST_QUEUE_URL="${QUEUE_URL//localstack:4566/host.docker.internal:4566}"
HOST_QUEUE_URL="${HOST_QUEUE_URL//localhost.localstack.cloud/host.docker.internal}"

cat >"${ENV_DIR}/simulation.host.env" <<EOF
# Host / SAM local env (see env.json StartSimulationFunction).
SQS_QUEUE_URL=${HOST_QUEUE_URL}
SQS_ENDPOINT=http://host.docker.internal:4566
EOF

# Keep env.json in sync so sam local start-api uses the same queue URL.
python3 <<PY
import json
from pathlib import Path

env_path = Path("env.json")
data = json.loads(env_path.read_text())
fn = data.setdefault("StartSimulationFunction", {})
fn["SQS_QUEUE_URL"] = "${HOST_QUEUE_URL}"
fn["SQS_ENDPOINT"] = "http://host.docker.internal:4566"
fn.setdefault("DELAY_STEP_SECONDS", "0")
env_path.write_text(json.dumps(data, indent=2) + "\n")
print("  Updated env.json StartSimulationFunction.SQS_QUEUE_URL")
PY

echo ""
echo "Simulation local stack ready."
echo "  SQS queue  : ${QUEUE_URL}"
echo "  DynamoDB   : ${TABLE_NAME}"
echo "  Docker env : ${ENV_FILE}"
echo ""
echo "Next: make start-api  (terminal 2)"
echo "      make demo-simulation  (terminal 3, after API is up)"
